### ISSUE TITLE
[OpenSage.Launcher] crashes with Unhandled exception

### ISSUE THREAD

**Issue by stevebone** [OpenSAGE/OpenSAGE#1009]
Master branch build, no custom changes and standard Generals content.

`[15:59:34.1807][Info] Starting...
[15:59:34.5192][Info] UPnP status: Enabled
[15:59:35.0033][Warn] [CSF] Number of labels and strings mismatch.
[15:59:35.5588][Info] FontFallback Settings loaded from Content\Fonts\FontFallbackSettings.json
[15:59:36.7697][Warn] Requested string 'MISSING: 'MAP:NoTest'' not found in 'en-US'.
[15:59:36.7697][Warn] Requested string 'MISSING: 'MAP:NoTest'' not found in 'en-US'.
[15:59:36.7697][Warn] Requested string 'MISSING: 'MAP:NoTest'' not found in 'en-US'.
[15:59:38.0038][Info] Weapon Comanche20mmCannonWeapon on game object  transitioning to state Inactive
[15:59:38.0038][Info] Weapon ComancheAntiTankMissileWeapon on game object  transitioning to state Inactive
[15:59:38.0399][Info] Set active condition state for AmericaVehicleComanche
[15:59:38.0469][Info] Set active animation state for AmericaVehicleComanche
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenSage.Logic.Object.AIUpdate..ctor(GameObject gameObject, GameContext context, AIUpdateModuleData moduleData) in L:\Github\OpenSage\src\OpenSage.Game\Logic\Object\Update\AIUpdate\AIUpdate.cs:line 103
   at OpenSage.Logic.Object.JetAIUpdate..ctor(GameObject gameObject, GameContext context, JetAIUpdateModuleData moduleData) in L:\Github\OpenSage\src\OpenSage.Game\Logic\Object\Update\AIUpdate\JetAIUpdate.cs:line 60
   at OpenSage.Logic.Object.JetAIUpdateModuleData.CreateModule(GameObject gameObject, GameContext context) in L:\Github\OpenSage\src\OpenSage.Game\Logic\Object\Update\AIUpdate\JetAIUpdate.cs:line 420
   at OpenSage.Logic.Object.GameObject..ctor(ObjectDefinition objectDefinition, GameContext gameContext, Player owner) in L:\Github\OpenSage\src\OpenSage.Game\Logic\Object\GameObject.cs:line 528
   at OpenSage.Logic.GameLogic.CreateObject(ObjectDefinition objectDefinition, Player player) in L:\Github\OpenSage\src\OpenSage.Game\Logic\GameLogic.cs:line 69
   at OpenSage.Logic.Object.GameObject.FromMapObject(MapObject mapObject, GameContext gameContext, Boolean useRotationAnchorOffset, Nullable`1& overwriteAngle) in L:\Github\OpenSage\src\OpenSage.Game\Logic\Object\GameObject.cs:line 56
   at OpenSage.Scene3D.LoadObjects(AssetLoadContext loadContext, HeightMap heightMap, MapObject[] mapObjects, NamedCameras namedCameras, WaypointCollection& waypointCollection, RoadCollection& roads, Bridge[]& bridges, CameraCollection& cameras) in L:\Github\OpenSage\src\OpenSage.Game\Scene3D.cs:line 198
   at OpenSage.Scene3D..ctor(Game game, MapFile mapFile, String mapPath, Int32 randomSeed, Player[] mapPlayers, Team[] mapTeams, ScriptList[] mapScriptLists, GameType gameType) in L:\Github\OpenSage\src\OpenSage.Game\Scene3D.cs:line 136
   at OpenSage.Game.LoadMap(String mapPath, PlayerSetting[] playerSettings, GameType gameType) in L:\Github\OpenSage\src\OpenSage.Game\Game.cs:line 631
   at OpenSage.Game.ShowMainMenu() in L:\Github\OpenSage\src\OpenSage.Game\Game.cs:line 601
   at OpenSage.Launcher.Program.Run(Options opts) in L:\Github\OpenSage\src\OpenSage.Launcher\Program.cs:line 231
   at OpenSage.Launcher.Program.<>c.<Main>b__1_1(Options opts) in L:\Github\OpenSage\src\OpenSage.Launcher\Program.cs:line 74
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at OpenSage.Launcher.Program.Main(String[] args) in L:\Github\OpenSage\src\OpenSage.Launcher\Program.cs:line 73`

**Comment by charliefoxtwo** [comment]
I believe this was fixed by #1076
