### ISSUE TITLE
OpenAL Linux problem

### ISSUE THREAD

**Issue by Nostritius** [OpenSAGE/OpenSAGE#135]
I experienced problems in the linux version of OpenSAGE regarding the OpenAL-CS library. 

> Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'soft_oal' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsoft_oal: cannot open shared object file: No such file or directory
   at OpenAL.ALC10.alcOpenDevice(String devicename)
   at OpenSage.Audio.AudioSystem..ctor(Game game) in /home/patrick/Workspace/OpenSAGE/src/OpenSage.Game/Audio/AudioSystem.cs:line 41
   at OpenSage.Game..ctor(IGameDefinition definition, FileSystem fileSystem, GamePanel panel) in /home/patrick/Workspace/OpenSAGE/src/OpenSage.Game/Game.cs:line 204
   at OpenSage.GameFactory.CreateGame(GameInstallation installation, FileSystem fileSystem, GamePanel panel) in /home/patrick/Workspace/OpenSAGE/src/OpenSage.Game/GameFactory.cs:line 34
   at OpenSage.Viewer.UI.MainForm.ChangeInstallation(GameInstallation installation) in /home/patrick/Workspace/OpenSAGE/src/OpenSage.Viewer/UI/MainForm.cs:line 272
   at OpenSage.Viewer.UI.MainForm..ctor(GameWindow gameWindow, ImGuiRenderer imGuiRenderer) in /home/patrick/Workspace/OpenSAGE/src/OpenSage.Viewer/UI/MainForm.cs:line 45
   at OpenSage.Viewer.Program.Main(String[] args) in /home/patrick/Workspace/OpenSAGE/src/OpenSage.Viewer/Program.cs:line 51

**Comment by Nostritius** [comment]
It was possible to circumvent the bug by creating a symbolic link from my system libopenal.so to libsoft_oal.so

**Comment by feliwir** [comment]
I’ll change this so the system openal is used on linux

**Comment by feliwir** [comment]
Adressed this by writing [SharpAudio](https://github.com/feliwir/SharpAudio), which uses system OpenAL on Linux. Will integrate this soon hopefully.

**Comment by feliwir** [comment]
@Nostritius can you check with the current master if the bug is still present?

**Comment by Nostritius** [comment]
Seems to be fixed with the new Audio system.
