### ISSUE TITLE
Mac CI builds intermittently failing

### ISSUE THREAD

**Issue by charliefoxtwo** [OpenSAGE/OpenSAGE#732]
Not sure what's going on here, but it seems like a fair percentage of Mac CI builds (but not all) fail.

I've seen this in a few recent ones. The test process is inexplicably crashing. 

```
The active test run was aborted. Reason: Test host process crashed

Test Run Aborted.
Passed!  - Failed:     0, Passed:   408, Skipped:     0, Total:   408, Duration: 517 ms - OpenSage.Game.Tests.dll (net7.0)

Attachments:
  /Users/runner/work/OpenSAGE/OpenSAGE/src/OpenSage.Game.Tests/TestResults/0f64397a-f94e-4d0b-90ac-64334233710a/coverage.cobertura.xml
Error: Process completed with exit code 1.
```

**Comment by Tarcontar** [comment]
Found one issue on my M1 Macbook Air that was solved with #745, my local runs work now but the issue still seems to persist.

**Comment by charliefoxtwo** [comment]
Looks like intermittent failures are occurring on Windows too
https://github.com/OpenSAGE/OpenSAGE/actions/runs/10192739178/job/28196110913
```
   OpenSage.Game.Tests -> D:\a\OpenSAGE\OpenSAGE\src\OpenSage.Game.Tests\bin\Release\net8.0\OpenSage.Game.Tests.dll
Test run for D:\a\OpenSAGE\OpenSAGE\src\OpenSage.Game.Tests\bin\Release\net8.0\OpenSage.Game.Tests.dll (.NETCoreApp,Version=v8.0)
Microsoft (R) Test Execution Command Line Tool Version 17.10.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[05:47:33.4781][Warn] No game installations found
[05:47:33.4928][Warn] No game installations found
[05:47:33.8298][Warn] No game installations found
[05:47:33.8298][Warn] No game installations found
[05:47:33.8298][Warn] No game installations found
[05:47:33.8298][Warn] No game installations found
[05:47:33.8443][Warn] No game installations found
[05:47:33.8443][Warn] No game installations found
[xUnit.net 00:00:00.70]     OpenSage.Tests.Scripting.ScriptConditionsTests.TestCounter [SKIP]
  Skipped OpenSage.Tests.Scripting.ScriptConditionsTests.TestCounter [1 ms]
[05:47:33.9369][Warn] No game installations found
[05:47:33.9369][Warn] No game installations found
[05:47:33.9369][Warn] No game installations found
[05:47:33.9369][Warn] No game installations found
The active test run was aborted. Reason: Test host process crashed : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Veldrid.Sdl2.Sdl2Native.SDL_Init(Veldrid.Sdl2.SDLInitFlags)
   at OpenSage.Platform.Start()
   at OpenSage.Tests.GameFixture..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
   at System.Reflection.ConstructorInfo.Invoke(System.Object[])
   at Xunit.Sdk.XunitTestClassRunner.CreateClassFixture(System.Type)
   at Xunit.Sdk.XunitTestClassRunner+<CreateClassFixtureAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.XunitTestClassRunner+<CreateClassFixtureAsync>d__11, xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<CreateClassFixtureAsync>d__11 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Xunit.Sdk.XunitTestClassRunner+<CreateClassFixtureAsync>d__11, xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<CreateClassFixtureAsync>d__11 ByRef)
   at Xunit.Sdk.XunitTestClassRunner.CreateClassFixtureAsync(System.Type)
   at Xunit.Sdk.XunitTestClassRunner+<AfterTestClassStartingAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.XunitTestClassRunner+<AfterTestClassStartingAsync>d__13, xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<AfterTestClassStartingAsync>d__13 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Xunit.Sdk.XunitTestClassRunner+<AfterTestClassStartingAsync>d__13, xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<AfterTestClassStartingAsync>d__13 ByRef)
   at Xunit.Sdk.XunitTestClassRunner.AfterTestClassStartingAsync()
   at Xunit.Sdk.TestClassRunner`1+<RunAsync>d__37[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestClassRunner`1+<RunAsync>d__37[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__37<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Xunit.Sdk.TestClassRunner`1+<RunAsync>d__37[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__37<System.__Canon> ByRef)
   at Xunit.Sdk.TestClassRunner`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync()
   at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(Xunit.Abstractions.ITestClass, Xunit.Abstractions.IReflectionTypeInfo, System.Collections.Generic.IEnumerable`1<Xunit.Sdk.IXunitTestCase>)
   at Xunit.Sdk.TestCollectionRunner`1+<RunTestClassesAsync>d__28[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestCollectionRunner`1+<RunTestClassesAsync>d__28[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunTestClassesAsync>d__28<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Xunit.Sdk.TestCollectionRunner`1+<RunTestClassesAsync>d__28[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunTestClassesAsync>d__28<System.__Canon> ByRef)
   at Xunit.Sdk.TestCollectionRunner`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunTestClassesAsync()
   at Xunit.Sdk.TestCollectionRunner`1+<RunAsync>d__27[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestCollectionRunner`1+<RunAsync>d__27[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__27<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Xunit.Sdk.TestCollectionRunner`1+<RunAsync>d__27[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__27<System.__Canon> ByRef)
   at Xunit.Sdk.TestCollectionRunner`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync()
   at Xunit.Sdk.XunitTestAssemblyRunner+<RunTestCollectionAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.XunitTestAssemblyRunner+<RunTestCollectionAsync>d__18, xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunTestCollectionAsync>d__18 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Xunit.Sdk.XunitTestAssemblyRunner+<RunTestCollectionAsync>d__18, xunit.execution.dotnet, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunTestCollectionAsync>d__18 ByRef)
   at Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(Xunit.Sdk.IMessageBus, Xunit.Abstractions.ITestCollection, System.Collections.Generic.IEnumerable`1<Xunit.Sdk.IXunitTestCase>, System.Threading.CancellationTokenSource)
   at Xunit.Sdk.XunitTestAssemblyRunner+<>c__DisplayClass16_2.<RunTestCollectionsAsync>b__2()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()


Passed!  - Failed:     0, Passed:   249, Skipped:     1, Total:   250, Duration: 207 ms - OpenSage.Game.Tests.dll (net8.0)
Test Run Aborted.
```

**Comment by charliefoxtwo** [comment]
Still occurring https://github.com/OpenSAGE/OpenSAGE/actions/runs/10543057885/job/29210566957

**Comment by charliefoxtwo** [comment]
Still occurring https://github.com/OpenSAGE/OpenSAGE/actions/runs/13800148233/job/38600748874

**Comment by charliefoxtwo** [comment]
Still occurring https://github.com/OpenSAGE/OpenSAGE/actions/runs/14274480502/job/40014774534 (this one on Windows)
